# -*- coding:utf-8 -*-
NORMAL_EXIT = 0
GENERAL_ERROR = 1
CONFIG_FILE_NOT_EXIST = 2
OSS_NOT_CONFIG = 3
JSON_NOT_VALID = 4
WOMTOOL_CAN_NOT_EXECUTE = 5
VALIDATE_ERROR = 6
APP_IS_INSTALLED = 7
SERVER_NOT_CONFIG = 8
USERNAME_NOT_VALID = 9
APP_INSTALL_FAILED = 10
NO_SUCH_KEY_IN_SECTION = 11
CONFIG_FILE_FAILED = 12
NOTESTFILE = 13
